#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# -- global settings --
yabai -m config external_bar                 all:24:0
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off 
yabai -m config window_placement             second_child   # new window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_topmost               on 
yabai -m config window_opacity               on 
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                float          # show shadows only for floating windows
yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config active_window_opacity        0.9
yabai -m config normal_window_opacity        0.5
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off 

# -- mouse settings --
yabai -m config mouse_modifier               alt            # modifier for clicking and dragging with mouse
yabai -m config mouse_action1                move           # set modifier + left-click drag to move window
yabai -m config mouse_action2                resize         # set modifier + right-click drag to resize window
yabai -m mouse_drop_action                   swap           # when window is dropped in center of another window, swap them (on edges it will split it)

# -- general space settings -- 
yabai -m config layout                       bsp
yabai -m config top_padding                  20 
yabai -m config bottom_padding               20
yabai -m config left_padding                 20
yabai -m config right_padding                20 
yabai -m config window_gap                   16

# -- disable specific apps --
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off
yabai -m rule --add app="^Skitch$" manage=off
yabai -m rule --add app="^Keymapp$" manage=off

yabai -m rule --apply
