# cSpell:ignore shellcheck powerline pomicons
# shellcheck disable=SC1001,SC1012
# vim:fileencoding=utf-8:foldmethod=marker

include                 theme.conf
hide_window_decorations titlebar-only
background_opacity      0.80
# window_padding_width    25
placement_strategy      top-left
font_family             CaskaydiaMono Nerd Font
font_size               14
disable_ligatures       never
shell_integration       no-title



map cmd+k send_text all \x02\x4b
map cmd+j send_text all \x02\x4a
map cmd+a send_text all \x02\x41
map cmd+r send_text all \x02\x52

map cmd send_test all \x02
map cmd+, send_text all \x02,
map cmd+, send_text all \x02:
map cmd+. send_text all \x1b\x20\x2e\x0a
map cmd+1 send_text all \x021
map cmd+2 send_text all \x022
map cmd+3 send_text all \x023
map cmd+4 send_text all \x024
map cmd+5 send_text all \x025
map cmd+6 send_text all \x026
map cmd+7 send_text all \x027
map cmd+8 send_text all \x028
map cmd+9 send_text all \x029
map cmd+[ send_text all \x0f
map cmd+] send_text all \x09
map cmd+e send_text all \x02\"
map cmd+g send_text all \x02g
map cmd+l send_text all \x02L
map cmd+o send_text all \x02u
map cmd+p send_text all :GoToFile\n
map cmd+r send_text all \x1b\x5b\x41\x0a
map cmd+s send_text all \x1b\x3a\x77\x0a
map cmd+shift+[ send_text all \x02p
map cmd+shift+] send_text all \x02n
map cmd+shift+c send_text all \x02\x20
map cmd+shift+e send_text all \x02%
map cmd+shift+f send_text all \x02\x5b\x2f
map cmd+shift+g send_text all \x02G
map cmd+shift+p send_text all :GoToCommand\n
map cmd+shift+s send_text all :wa\n
map cmd+shift+v send_text all \x02\x5d
map cmd+t send_text all \x02c
map cmd+w send_text all \x02x
map cmd+z send_text all \x02z


map kitty_mod+f5 load_config_file

update_check_interval 0

editor vim
cursor_trail 3
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 10

# Customize fonts for symbols

# modify_font cell_width 100%
# modify_font cell_height 2px
# modify_font baseline 3

modify_font cell_height 4px
modify_font cell_width 100%
modify_font baseline 0
modify_font underline_position 5
modify_font underline_thickness 150%
modify_font strikethrough_position 2px

dynamic_background_opacity yes
background_blur 12
window_padding_width  24 32